image:
  # Specify a base image if you need a custom environment, or use a Ruby image.
  # You can start with the default Ruby image, for example:
  # image: gitpod/workspace-ruby

tasks:
  - name: Install gems and run RSpec
    init:
      - gem install rspec
      - gem install selenium-webdriver
    command: |
      # Run RSpec command after installation
      rspec parallel_tests.rb
