image: gitpod/workspace-ruby:latest

tasks:
  - init: |
      # Install the required gems
      gem install rspec
      gem install selenium-webdriver  # Replace with the second gem you need
    command: |
      # Run the RSpec tests
      rspec parallel_tests.rb # Replace with the actual path to your RSpec file

ports:
  - port: 3000
    onOpen: open-preview
