
tasks:
  - name: Install gems and run RSpec
    init:
      - gem install rspec
      - gem install selenium-webdriver
    command: |
      # Run RSpec command after installation
      rspec parallel_tests.rb
